#
# Ansible の Playbook です。
# GitHub から落としてきた Laravel アプリケーションをローカルコンピューター上にデプロイします。
#

---
  - hosts: localhost
    become: yes
    become_method: sudo
    tasks:

      - name: create /var/www/ directory
        file: dest=/var/www/ state=directory owner=root group=root mode=0755

      - name: Cloning Project
        git: >
            dest=/var/www/peta
            repo=https://github.com/aklabo/peta.git
            update=yes
            accept_hostkey=yes
        become: yes
        become_user: apache
        # 毎回 create-project してしまい、APP_KEY が変化するのを防ぐ
        register: cloned
      
      - name: composer create-project
        composer: >
            command=create-project
            working_dir=/var/www/peta/peta-core
            optimize_autoloader=no
        become: yes
        become_user: apache
        # 毎回 create-project してしまい、APP_KEY が変化するのを防ぐ
        when: cloned|changed
